spring:
  application:
    name: board

  #mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 0
      port: 6379
      host: 127.0.0.1
      password:
  cache:
    redis:
      time-to-live: 10000


#@Value redis
redis:
  host: 127.0.0.1
  port: 6379
  password:
  time-to-live: 10000
